---

- name: create icingadb configuration
  ansible.builtin.template:
    src: etc/icingadb/config.yml.j2
    dest: /etc/icingadb/config.yml
    owner: "{{ icingadb_user }}"
    group: "{{ icingadb_group }}"
    mode: 0640
    backup: true
  notify:
    - restart icingadb

- name: create directory for logfiles
  ansible.builtin.file:
    state: directory
    owner: "{{ icingadb_user }}"
    group: "{{ icingadb_group }}"
    mode: 0750
    path: /var/log/icingadb

- name: ensure table_schema is created
  bodsch.core.mysql_schema:
    login_host: "{{ icingadb_database.host }}"
    login_user: "{{ icingadb_database.user }}"
    login_password: "{{ icingadb_database.password }}"
    table_schema: "{{ icingadb_database.database }}"
  no_log: true
  register: mysql_icingawebdb_schema
  when:
    - icingadb_database is defined
    - icingadb_database.host is defined
    - icingadb_database.user is defined
    - icingadb_database.password is defined
    - icingadb_database.database is defined

- name: database
  when:
    - mysql_icingawebdb_schema is defined
    - mysql_icingawebdb_schema.exists is defined
    - not mysql_icingawebdb_schema.exists
  block:
    - name: import database schema
      community.mysql.mysql_db:
        state: import
        login_host: "{{ icingadb_database.host }}"
        login_user: "{{ icingadb_database.user }}"
        login_password: "{{ icingadb_database.password }}"
        config_file: ''
        name: "{{ icingadb_database.database }}"
        target: '{{ icingadb_install_dir }}/schema/mysql/schema.sql'
      no_log: true
      register: icingawebdb_database_schema

    - name: error
      ansible.builtin.fail:
        msg:
          - "ERROR: {{ icingawebdb_database_schema }}"
      when:
        - mysql_icingawebdb_schema is defined
        - mysql_icingawebdb_schema.failed is defined
        - mysql_icingawebdb_schema.failed

...
